server:
  port: 8080
spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: http://oauth2:8080
              predicates:
                - Path=/auth/**
            - id: user-service
              uri: http://oauth2:8080
              predicates:
                - Path=/users/**
            - id: notebook-service
              uri: http://notebook:8080
              predicates:
                - Path=/sync/**